import fs from "fs";
import path from "path";

const outDir = path.join(process.cwd(), "content/ptils");
fs.mkdirSync(outDir, { recursive: true });

function writeMdx(number, { title, prompt, whyItWorks, exampleOutput, tags, worksWith, createdAt }) {
  const id = `ptil-${String(number).padStart(3, "0")}`;
  const filename = `${String(number).padStart(3, "0")}.mdx`;
  const ws = worksWith || ["Claude", "GPT-4", "Gemini"];
  const date = createdAt || "2025-01-15";

  const content = `---
id: "${id}"
number: ${number}
title: "${title.replace(/"/g, '\\"')}"
prompt: "${prompt.replace(/"/g, '\\"').replace(/\n/g, "\\n")}"
tags: [${tags.map((t) => `"${t}"`).join(", ")}]
worksWith: [${ws.map((w) => `"${w}"`).join(", ")}]
createdAt: "${date}"
---

## Why It Works

${whyItWorks}

## Example Output

${exampleOutput}
`;

  fs.writeFileSync(path.join(outDir, filename), content);
  console.log(`Wrote ${filename}`);
}

// ── Existing 25 PTILs ──────────────────────────────────────────────
const existing = [
  {
    title: "You can ask Claude to critique its own output and improve it in one go",
    prompt: "Write a product description for [X], then critique it for clarity and persuasiveness, then write an improved version.",
    whyItWorks: "Self-critique forces the model to evaluate from a reader's perspective before revising. This mimics the revision process of expert writers and often produces significantly better output than a single pass.",
    exampleOutput: "**First draft:** Our app helps you manage tasks...\n\n**Critique:** This is generic and doesn't highlight unique value...\n\n**Improved:** Take back your mornings. TaskFlow uses AI to prioritize what actually matters...",
    tags: ["writing", "self-critique", "productivity"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can give Claude a persona to get more specialized responses",
    prompt: "You are a senior staff engineer at a FAANG company with 15 years of experience. Review this code and give me the feedback you'd give a junior engineer on your team.",
    whyItWorks: "Personas activate domain-specific knowledge and communication styles. A 'senior engineer' persona will catch architectural issues and provide mentorship-style feedback that a generic review wouldn't.",
    exampleOutput: "A few things I'd flag in code review:\n\n1. **Naming:** `processData` tells me nothing...",
    tags: ["coding", "personas", "code-review"],
    worksWith: ["Claude", "GPT-4"],
  },
  {
    title: "You can ask for multiple options and then have the AI pick the best one",
    prompt: "Give me 5 different taglines for [product]. Then evaluate each on clarity, memorability, and emotional impact. Finally, recommend which one to use and why.",
    whyItWorks: "Generating options first expands the solution space. Having the AI evaluate its own options leverages its judgment while giving you transparency into the reasoning.",
    exampleOutput: "**Options:**\n1. 'Your data, decoded.'\n2. 'Insights in seconds.'...\n\n**Evaluation:**...\n\n**Recommendation:** Option 3 because...",
    tags: ["brainstorming", "decision-making", "marketing"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to explain something at multiple levels of complexity",
    prompt: "Explain [concept] three ways: first to a 10-year-old, then to a college student, then to an expert in the field.",
    whyItWorks: "This forces the model to truly understand the concept at different depths. It's also a great way to find the explanation level that works for your audience.",
    exampleOutput: "**For a 10-year-old:** Imagine you have a bunch of LEGO pieces...\n\n**For a college student:** Machine learning is a subset of AI...\n\n**For an expert:** Transformer architectures leverage self-attention mechanisms...",
    tags: ["learning", "explanation", "teaching"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can use 'thinking out loud' to get better reasoning",
    prompt: "Think through this step-by-step, showing your reasoning at each stage: [problem]",
    whyItWorks: "Chain-of-thought prompting improves accuracy on complex tasks by forcing the model to show intermediate steps rather than jumping to conclusions.",
    exampleOutput: "Let me work through this step by step:\n\n**Step 1:** First, I need to understand...\n**Step 2:** Given that, the next consideration is...",
    tags: ["reasoning", "problem-solving", "chain-of-thought"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask for the devil's advocate perspective",
    prompt: "I'm considering [decision]. First, make the strongest possible case in favor. Then, play devil's advocate and make the strongest case against. Finally, give me your balanced assessment.",
    whyItWorks: "This overcomes confirmation bias by forcing consideration of opposing views. The balanced assessment at the end synthesizes both perspectives.",
    exampleOutput: "**Case in favor:** The data clearly shows...\n\n**Devil's advocate:** However, we should consider...\n\n**Balanced view:** Weighing both sides...",
    tags: ["decision-making", "critical-thinking", "analysis"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can constrain the format to get more usable output",
    prompt: "Summarize this article in exactly 3 bullet points, where each bullet is one sentence and under 20 words.",
    whyItWorks: "Constraints force precision. Without them, summaries tend to be verbose. Specific word/sentence limits make output immediately usable.",
    exampleOutput: "• The study found remote workers were 13% more productive than office counterparts.\n• Collaboration suffered, with team projects taking 20% longer to complete.\n• Hybrid models (2-3 days remote) showed the best balance of both metrics.",
    tags: ["summarization", "formatting", "constraints"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to write in a specific author's style",
    prompt: "Explain [topic] in the style of [author]. Capture their voice, sentence structure, and typical metaphors.",
    whyItWorks: "Style mimicry helps when you need a specific tone. It's also a great way to make dry topics more engaging by channeling a compelling voice.",
    exampleOutput: "**In the style of David Foster Wallace:**\n\nSo here's the thing about machine learning, and it's the kind of thing that seems obvious once you think about it but which nobody actually thinks about...",
    tags: ["writing", "style", "creative"],
    worksWith: ["Claude", "GPT-4"],
  },
  {
    title: "You can ask for a pre-mortem analysis",
    prompt: "Imagine it's 6 months from now and [project/decision] has completely failed. What went wrong? Give me the 5 most likely reasons for failure.",
    whyItWorks: "Pre-mortems surface risks that optimism bias hides. By assuming failure, you identify vulnerabilities you'd otherwise overlook.",
    exampleOutput: "**Post-mortem from the future:**\n\n1. We underestimated the technical complexity of...\n2. The market shifted when competitor X...\n3. Team burnout became critical after...",
    tags: ["planning", "risk-analysis", "decision-making"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can use examples to calibrate the output you want",
    prompt: "Write a tweet about [topic]. Here are examples of the tone I want:\\n\\n- 'Just mass unfollowed 50 tech bros. Hygiene.'\\n- 'Hot take: your startup doesn't need AI, it needs a user manual.'\\n\\nNow write 5 tweets in this style about [topic].",
    whyItWorks: "Few-shot examples are more precise than adjectives. Instead of saying 'witty and sarcastic,' showing examples calibrates the exact tone.",
    exampleOutput: "1. 'Your AI assistant doesn't have hallucinations, it has creative differences.'\n2. 'Just prompted ChatGPT to write my OKRs. Finally, corporate speak that makes sense.'...",
    tags: ["few-shot", "social-media", "tone"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to identify what's missing",
    prompt: "Here's my plan for [X]. What am I missing? What questions should I be asking that I haven't thought of?",
    whyItWorks: "You don't know what you don't know. This prompt surfaces blind spots and unknown unknowns that your own thinking can't access.",
    exampleOutput: "Your plan looks solid, but here are some gaps I'd flag:\n\n1. **Distribution:** You've detailed the product but not how people will discover it...\n2. **Edge cases:** What happens when...",
    tags: ["planning", "blind-spots", "review"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask for feedback as a specific type of user",
    prompt: "Review this landing page copy as if you're a skeptical enterprise buyer who's been burned by SaaS vendors before. What concerns would you have?",
    whyItWorks: "User personas in feedback prompts surface objections you'd miss. Different personas catch different issues.",
    exampleOutput: "**As a skeptical enterprise buyer:**\n\n'Sounds great, but I've heard this before. My concerns:\n\n1. Where's the case study from a company my size?\n2. 'AI-powered' means what exactly?...'",
    tags: ["feedback", "personas", "marketing"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can have Claude roleplay both sides of a conversation",
    prompt: "Simulate a conversation between a skeptical customer and a sales rep about [product]. The customer has objection [X]. Show how the conversation would unfold over 5 exchanges.",
    whyItWorks: "Dialogue simulation helps you anticipate objections and practice responses. It's like a rehearsal for real conversations.",
    exampleOutput: "**Customer:** Look, I've tried three tools like this already. Why would yours be different?\n\n**Sales rep:** Totally fair question. What specifically didn't work about the others?...",
    tags: ["sales", "roleplay", "objection-handling"],
    worksWith: ["Claude", "GPT-4"],
  },
  {
    title: "You can ask for progressively deeper explanations",
    prompt: "Explain [concept]. Then explain the most complex part of what you just said. Then explain the most complex part of that.",
    whyItWorks: "Recursive explanation drills into the hardest parts automatically. Each layer unpacks the previous layer's complexity.",
    exampleOutput: "**Level 1:** Neural networks learn patterns by adjusting connection weights based on errors.\n\n**Level 2:** 'Adjusting weights based on errors' means...\n\n**Level 3:** 'Gradient descent' works by...",
    tags: ["learning", "explanation", "deep-dive"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to steelman an argument you disagree with",
    prompt: "I think [position]. But I want to understand the other side. Give me the strongest possible argument against my position, as if you were a skilled debater who genuinely believes it.",
    whyItWorks: "Steelmanning builds empathy and stress-tests your own position. Understanding the best opposing argument makes your own thinking sharper.",
    exampleOutput: "**Steelman against your position:**\n\nThe most compelling counterargument isn't the obvious one. Here's the sophisticated version:\n\n1. You're assuming [X], but what if...",
    tags: ["critical-thinking", "debate", "analysis"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask for the 80/20 breakdown",
    prompt: "I want to learn [skill/topic]. What's the 20% I need to learn that will give me 80% of the practical value? Ignore the advanced stuff — what are the fundamentals that matter most?",
    whyItWorks: "This cuts through the completionist urge to learn everything. It prioritizes high-leverage knowledge for practical application.",
    exampleOutput: "**The 80/20 of SQL:**\n\nForget stored procedures and window functions for now. Master these:\n\n1. SELECT, FROM, WHERE (90% of your queries)\n2. JOIN (just LEFT JOIN honestly)...",
    tags: ["learning", "productivity", "prioritization"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to find the flaw in your logic",
    prompt: "Here's my argument: [argument]. Attack this logic. Find the weakest points, hidden assumptions, and logical fallacies. Don't be nice about it.",
    whyItWorks: "Inviting criticism surfaces flaws you're blind to. The 'don't be nice' instruction overrides the model's tendency to be agreeable.",
    exampleOutput: "**Problems with your argument:**\n\n1. **Hidden assumption:** You're assuming correlation implies causation when you say...\n2. **Cherry-picked evidence:** The data points you chose ignore...\n3. **Logical gap:** Even if A→B and B→C, you haven't shown...",
    tags: ["logic", "critical-thinking", "argumentation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask for the 'explain like I'm' format at any level",
    prompt: "Explain [complex topic] like I'm a smart 12-year-old who's curious but has no background in this field.",
    whyItWorks: "The 'smart but uninformed' framing hits a sweet spot: no jargon, but no condescension. It forces clear explanations without oversimplification.",
    exampleOutput: "So you know how when you're trying to find your friend in a crowd, you look for things that stand out — like their red jacket or how tall they are? Machine learning does something similar...",
    tags: ["explanation", "learning", "simplification"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to reverse-engineer a goal",
    prompt: "I want to achieve [outcome] in [timeframe]. Work backwards from the goal: what would need to be true 1 month before? 1 week before? What should I do tomorrow?",
    whyItWorks: "Backward planning from the goal creates concrete stepping stones. It's easier to plan forward once you've mapped backward.",
    exampleOutput: "**Goal:** Launch product in 3 months\n\n**1 month before launch:** Beta testing complete, landing page live, waitlist of 500+\n\n**1 week before:** Final bug fixes, press outreach sent...\n\n**Tomorrow:** Finish MVP spec, reach out to 3 beta testers",
    tags: ["planning", "goals", "productivity"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask for analogies from different domains",
    prompt: "Explain [concept] using an analogy from cooking. Then explain it using an analogy from sports. Then from music.",
    whyItWorks: "Multiple analogies from different domains reveal different facets of the concept. One of them will click for any given learner.",
    exampleOutput: "**Cooking analogy:** APIs are like a restaurant menu. You don't need to know how the kitchen works — you just order from the menu and get what you asked for...\n\n**Sports analogy:** APIs are like the rules of basketball...",
    tags: ["explanation", "analogies", "learning"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to compress information ruthlessly",
    prompt: "Summarize [long text] in exactly 50 words. Every word must earn its place. No filler, no fluff.",
    whyItWorks: "Extreme compression forces prioritization. The constraint eliminates 'nice to have' details and keeps only what's essential.",
    exampleOutput: "The study tracked 10,000 remote workers over two years. Key finding: productivity rose 13% but collaboration declined. Teams took longer on joint projects. Hybrid arrangements (2-3 remote days) optimized both metrics. Recommendation: mandate overlap days for synchronous work.",
    tags: ["summarization", "constraints", "writing"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask for a second opinion from a different perspective",
    prompt: "I got this advice: [advice]. Now pretend you're a completely different expert with an opposing philosophy. What advice would you give instead, and why might the original advice be wrong?",
    whyItWorks: "Single perspectives have blind spots. Forcing an opposing viewpoint reveals assumptions and alternatives you'd otherwise miss.",
    exampleOutput: "**Original advice:** 'Move fast and break things.'\n\n**Opposing expert (risk-averse CTO):** 'That philosophy created the mess we're cleaning up now. Here's why careful iteration beats speed...'",
    tags: ["decision-making", "perspectives", "advice"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to create a decision framework",
    prompt: "I need to decide between [options]. Create a scoring rubric with 5 weighted criteria. Then score each option and show me the math.",
    whyItWorks: "Structured frameworks externalize your reasoning and make trade-offs explicit. The scoring forces you to quantify gut feelings.",
    exampleOutput: "**Criteria (weighted):**\n1. Cost (25%)\n2. Time to implement (20%)...\n\n**Scoring:**\n| Option | Cost | Time | ... | Total |\n|--------|------|------|-----|-------|\n| A      | 8    | 6    | ... | 7.2   |",
    tags: ["decision-making", "frameworks", "analysis"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask for 'yes, and' brainstorming",
    prompt: "I have an idea: [idea]. Instead of critiquing it, build on it. Give me 5 ways to make it bigger, bolder, or more interesting. Say 'yes, and...' to each addition.",
    whyItWorks: "Improv-style brainstorming suspends judgment and expands possibilities. Criticism kills ideas early; 'yes, and' lets them grow first.",
    exampleOutput: "**Yes, and** what if you also made it multiplayer?\n**Yes, and** what if there was a leaderboard?\n**Yes, and** what if the top contributors got featured...",
    tags: ["brainstorming", "creativity", "ideation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask Claude to translate jargon for different audiences",
    prompt: "Take this technical explanation: [text]. Rewrite it for: 1) An executive who has 30 seconds, 2) A non-technical teammate, 3) A customer FAQ.",
    whyItWorks: "The same information needs different framings for different audiences. This prompt does the translation work for you.",
    exampleOutput: "**For executive (30 sec):** We reduced server costs 40% by switching to serverless. No downtime, same performance.\n\n**For teammate:** Instead of paying for servers 24/7, we now only pay when someone actually uses the app...\n\n**For FAQ:** Your app will be just as fast, and we can offer this at a lower price because...",
    tags: ["communication", "translation", "audience"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
];

// ── New 100 curated prompts (from awesome-chatgpt-prompts + similar) ──
const newPrompts = [
  {
    title: "You can ask AI to simulate a Linux terminal",
    prompt: "I want you to act as a linux terminal. I will type commands and you will reply with what the terminal should show. Only reply with the terminal output inside one unique code block, and nothing else. Do not write explanations. Do not type commands unless I instruct you to do so.",
    whyItWorks: "Simulating a terminal lets you practice commands, debug scripts, and prototype workflows without risking your real system. The AI maintains state across commands just like a real shell session.",
    exampleOutput: "$ pwd\n/home/user\n\n$ ls -la\ntotal 24\ndrwxr-xr-x  4 user user 4096 Jan 15 09:00 .\ndrwxr-xr-x  3 root root 4096 Jan 10 12:00 ..\n-rw-r--r--  1 user user  220 Jan 10 12:00 .bash_profile",
    tags: ["programming", "simulation", "terminal"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to translate and upgrade your English",
    prompt: "I will speak to you in any language and you will detect the language, translate it, and answer in a corrected and improved version of my text in English. Replace my simplified words with more elegant, literary English. Keep the meaning the same. Only reply with the correction, no explanations.",
    whyItWorks: "This combines translation with style improvement in one step. The model acts as both translator and writing coach, upgrading vocabulary while preserving your intent.",
    exampleOutput: "**Input:** 'Je pense que ce projet est tres bon mais il a des problemes.'\n\n**Output:** 'I believe this project shows considerable promise, though it faces several notable challenges.'",
    tags: ["language", "writing", "translation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to conduct a mock job interview",
    prompt: "Act as an interviewer for the position of [role]. Ask me questions one by one like a real interviewer does and wait for my answers. Do not write all the questions at once. Start with 'Tell me about yourself.'",
    whyItWorks: "Practicing interviews with AI lets you rehearse answers, get feedback, and build confidence without the pressure of a real interview. The one-at-a-time format mimics actual interview flow.",
    exampleOutput: "**Interviewer:** Tell me about yourself.\n\n*[You answer]*\n\n**Interviewer:** That's interesting. Can you tell me about a time you had to deal with a difficult technical challenge?",
    tags: ["career", "interview-prep", "roleplay"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to act as a JavaScript console",
    prompt: "Act as a JavaScript console. I will type commands and you will reply with what the console should show. Only reply with the terminal output inside one unique code block. Do not write explanations. Do not type commands unless I instruct you to do so.",
    whyItWorks: "Quick prototyping without opening a browser. Test snippets, check API behavior, and validate logic in a conversational flow.",
    exampleOutput: "> [1, 2, 3].map(x => x * 2)\n[2, 4, 6]\n\n> typeof null\n'object'\n\n> Promise.resolve(42).then(console.log)\n42",
    tags: ["programming", "javascript", "simulation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to simulate a text-based spreadsheet",
    prompt: "Act as a text based Excel. Only reply with a text-based 10-row sheet with row numbers and columns (A to L). I will tell you what to write into cells and you'll reply only with the result of the table as text. When I write formulas, execute them and show the result.",
    whyItWorks: "Quick calculations and data organization without opening a spreadsheet app. Great for brainstorming tables, budgets, or data structures on the fly.",
    exampleOutput: "   | A        | B      | C     |\n1  | Product  | Price  | Qty   |\n2  | Widget A | 10.00  | 50    |\n3  | Widget B | 25.00  | 30    |\n4  | Total    | =SUM   | 1250  |",
    tags: ["productivity", "spreadsheet", "simulation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to be your spoken English practice partner",
    prompt: "Act as a spoken English teacher and improver. I will speak to you in English and you will reply to me in English to practice my spoken English. Keep your reply neat, limiting it to 100 words. Strictly correct my grammar mistakes, typos, and factual errors. Ask me a question in your reply. Let's start.",
    whyItWorks: "Having a patient, always-available conversation partner who corrects mistakes in real-time accelerates language learning. The 100-word limit keeps responses digestible.",
    exampleOutput: "**You:** 'I go to store yesterday and buyed some foods.'\n\n**AI:** 'I went to the store yesterday and bought some food.' — Note: 'go' becomes 'went' in past tense, and 'food' is typically uncountable. What kind of food did you buy?",
    tags: ["language", "conversation", "education"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to be your personal travel guide",
    prompt: "Act as a travel guide. I will tell you my location and you will suggest places to visit nearby. I may also specify the type of places I want. Suggest similar places close to my first location.",
    whyItWorks: "AI can cross-reference thousands of destinations and tailor recommendations to your preferences, budget, and location — like a knowledgeable local friend in every city.",
    exampleOutput: "**You:** I'm in Kyoto and love quiet temples.\n\n**AI:** Start with Ryoan-ji for its famous rock garden. Then walk to Kinkaku-ji (Golden Pavilion). For something off the beaten path, visit Tofuku-ji — stunning in autumn with far fewer tourists...",
    tags: ["travel", "recommendations", "lifestyle"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create an advertising campaign from scratch",
    prompt: "Act as an advertiser. Create a campaign to promote [product/service]. Choose a target audience, develop key messages and slogans, select media channels for promotion, and decide on additional activities to reach your goals.",
    whyItWorks: "This gives you a full marketing strategy in minutes — audience targeting, messaging, channels, and tactics — that would normally require a team brainstorm.",
    exampleOutput: "**Target:** Remote workers aged 25-40 who value productivity\n\n**Slogan:** 'Less tab juggling. More deep work.'\n\n**Channels:** LinkedIn sponsored content, productivity YouTube channels, Product Hunt launch...",
    tags: ["marketing", "business", "creative"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to be your motivational coach",
    prompt: "Act as a motivational coach. I will provide information about my goals and challenges, and your job is to come up with strategies to help me achieve them. This could include positive affirmations, helpful advice, or suggesting activities to reach my end goal.",
    whyItWorks: "A coach who knows your context can offer tailored strategies instead of generic advice. The AI adapts its suggestions to your specific situation and challenges.",
    exampleOutput: "**You:** I want to start a side project but I keep procrastinating.\n\n**Coach:** Let's start small. Commit to just 15 minutes tonight — set a timer. The hardest part is starting. Also, tell one friend about your project today. External accountability works...",
    tags: ["productivity", "motivation", "self-improvement"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to debate both sides of any topic",
    prompt: "Act as a debater. I will provide a topic and your task is to research both sides of the debate, present valid arguments for each side, refute opposing points, and draw persuasive conclusions based on evidence.",
    whyItWorks: "Seeing both sides of an argument structured and articulated helps you form better opinions, prepare for discussions, and identify the strongest points on each side.",
    exampleOutput: "**Topic:** Remote work vs. office work\n\n**For remote:** Studies show 13% productivity increase, elimination of commute...\n\n**For office:** Serendipitous collaboration, stronger culture, clearer work-life boundaries...\n\n**Conclusion:** The evidence suggests hybrid models capture most benefits of both...",
    tags: ["critical-thinking", "debate", "education"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write a screenplay scene",
    prompt: "Act as a screenwriter. Develop a scene for a [genre] film. Include character descriptions, setting, dialogue, and stage directions. Create an engaging narrative with tension and a turning point.",
    whyItWorks: "Screenwriting requires specific formatting and pacing that AI handles well. You get properly structured scenes with dialogue, action lines, and dramatic beats.",
    exampleOutput: "INT. COFFEE SHOP - DAY\n\nSARAH (30s, sharp eyes, fidgeting with her phone) sits across from MARK (40s, calm, overdressed for a coffee meeting).\n\nSARAH: You said you had something important.\n\nMARK: (sliding a folder across the table) I found your sister...",
    tags: ["creative-writing", "film", "storytelling"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write and critique a movie review",
    prompt: "Act as a movie critic. Write a review of [movie] covering plot, themes, acting, direction, cinematography, and score. Emphasize how the movie made you feel. Avoid spoilers.",
    whyItWorks: "A structured review framework ensures you cover all aspects of a film. The 'how it made you feel' instruction adds the subjective perspective that makes reviews compelling.",
    exampleOutput: "**The Holdovers** feels like a warm sweater on a cold day. Alexander Payne crafts a holiday film that earns its emotions through character rather than sentiment. Paul Giamatti's crusty professor is both infuriating and heartbreaking...",
    tags: ["entertainment", "writing", "reviews"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to help resolve relationship conflicts",
    prompt: "Act as a relationship coach. I will describe a conflict between two people, and your job is to suggest how they can work through the issues. Include communication techniques and strategies for improving understanding of each other's perspectives.",
    whyItWorks: "An outside perspective on conflicts can reveal communication patterns and blind spots. The AI offers techniques like active listening and reframing that therapists actually use.",
    exampleOutput: "**Technique 1: Mirror and validate.** Before responding, repeat back what you heard: 'What I'm hearing is that you feel overwhelmed when I...' This alone defuses most arguments.\n\n**Technique 2:** Use 'I feel' instead of 'You always'...",
    tags: ["relationships", "communication", "advice"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write evocative poetry",
    prompt: "Act as a poet. Write a poem about [theme] that evokes deep emotion. Use vivid imagery, metaphor, and rhythm. Make each word earn its place.",
    whyItWorks: "Poetry benefits from constraint and precision. Specifying the theme while asking for emotional depth and craft pushes the AI beyond generic verse into something resonant.",
    exampleOutput: "**The Weight of Empty Chairs**\n\nThe table set for four,\nthree plates collecting dust like years.\nI still pour the extra glass of wine —\nforce of habit, or of hope.",
    tags: ["creative-writing", "poetry", "art"],
    worksWith: ["Claude", "GPT-4"],
  },
  {
    title: "You can ask AI to teach philosophy in plain language",
    prompt: "Act as a philosophy teacher. I will name a concept and you will explain it in simple, accessible terms. Use everyday examples, pose thought-provoking questions, and break complex ideas into digestible pieces.",
    whyItWorks: "Philosophy is full of jargon that obscures genuinely useful ideas. Translating to plain language with real examples makes these concepts practical and immediately applicable.",
    exampleOutput: "**Concept: Existentialism**\n\nImagine you wake up in a room with no instructions, no manual, nothing telling you what to do. That's existentialism's starting point: there's no pre-written purpose for your life. You have to create your own meaning...",
    tags: ["philosophy", "education", "critical-thinking"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to tutor you through math step by step",
    prompt: "Act as a math teacher. I will provide a math problem and you will explain it step-by-step in easy-to-understand terms. Show your work at each step and explain why you're doing what you're doing.",
    whyItWorks: "Step-by-step math with explanations of the 'why' — not just the 'how' — builds real understanding rather than rote memorization.",
    exampleOutput: "**Problem:** Solve 2x + 5 = 17\n\n**Step 1:** Subtract 5 from both sides → 2x = 12\n*Why: We want x alone, so we remove the +5*\n\n**Step 2:** Divide both sides by 2 → x = 6\n*Why: 2x means '2 times x', so we undo the multiplication*",
    tags: ["math", "education", "tutoring"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to improve your writing with specific feedback",
    prompt: "Act as a writing tutor. I will give you my text and you will provide specific feedback on how to improve it. Use your knowledge of effective writing techniques to suggest better ways to express the ideas. Be specific — point to exact sentences.",
    whyItWorks: "Generic feedback like 'make it clearer' doesn't help. Pointing to specific sentences and offering concrete rewrites teaches you to recognize and fix your own patterns.",
    exampleOutput: "**Your sentence:** 'The utilization of this methodology enables optimization of outcomes.'\n\n**Feedback:** This is corporate fog. Every word is abstract. Try: 'This method gets better results.' Same meaning, half the words, twice the clarity.",
    tags: ["writing", "education", "feedback"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to improve your UX designs",
    prompt: "Act as a UX/UI consultant. I will describe my app's design and you will suggest creative improvements to the user experience. Consider usability, accessibility, visual hierarchy, and common UX patterns.",
    whyItWorks: "A fresh pair of eyes on your design catches issues you've become blind to. The AI applies UX principles systematically across every element.",
    exampleOutput: "**Issue 1:** Your signup form has 8 fields visible at once — that's intimidating. Break it into a 3-step wizard with a progress bar.\n\n**Issue 2:** The CTA button is the same color as the background. Make it your primary accent color and add 16px padding...",
    tags: ["design", "UX", "product"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to develop a cybersecurity strategy",
    prompt: "Act as a cybersecurity specialist. I will describe how data is stored and shared in my system, and you will suggest strategies for protecting it — encryption methods, firewall rules, access policies, and monitoring for suspicious activity.",
    whyItWorks: "Security is often an afterthought. This prompt forces a systematic review of your data flow and surfaces vulnerabilities you might not have considered.",
    exampleOutput: "**Critical findings:**\n\n1. API keys stored in plaintext in .env committed to git — rotate immediately and add to .gitignore\n2. No rate limiting on login endpoint — add brute-force protection\n3. User data transmitted over HTTP in staging — enforce HTTPS everywhere...",
    tags: ["security", "technology", "strategy"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to be your life coach",
    prompt: "Act as a life coach. I will share details about my current situation and goals, and you will suggest strategies to help me make better decisions and reach those objectives. This could include advice on planning, managing emotions, or building habits.",
    whyItWorks: "A life coach helps you see the forest when you're stuck in the trees. The AI can suggest frameworks for decision-making and habit-building that you might not discover on your own.",
    exampleOutput: "**Your situation:** You want to switch careers but feel stuck.\n\n**Strategy 1:** Don't quit yet. Start a '5% experiment' — spend 5% of your week (2 hours) on the new direction. Low risk, real data.\n\n**Strategy 2:** Talk to 3 people already doing what you want. Most career anxiety comes from imagining, not knowing...",
    tags: ["self-improvement", "coaching", "life-advice"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to trace the origin of any word",
    prompt: "Act as an etymologist. I will give you a word and you will research its origin, tracing it back to its ancient roots. Explain how the meaning has changed over time.",
    whyItWorks: "Etymology reveals hidden connections between words and ideas. Understanding origins makes vocabulary stick and gives you deeper insight into language.",
    exampleOutput: "**Word: 'Salary'**\n\nFrom Latin 'salarium' — literally 'salt money.' Roman soldiers were sometimes paid in salt, which was valuable for preserving food. This is also where 'worth your salt' comes from. The meaning shifted from literal salt payment to any regular compensation by the medieval period.",
    tags: ["language", "history", "education"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to give you career counseling",
    prompt: "Act as a career counselor. I will describe my skills, interests, and experience, and you will help me determine which careers I'm best suited for. Research available options, explain job market trends, and suggest qualifications that would help.",
    whyItWorks: "Career decisions benefit from structured analysis rather than gut feeling. The AI can map your skills to roles you might not have considered and highlight realistic paths.",
    exampleOutput: "**Your profile:** Strong writing, basic data analysis, psychology degree, 3 years in customer success.\n\n**Top matches:**\n1. UX Researcher — your psych background + customer empathy is exactly what this role needs\n2. Content Strategist — your writing + data skills are rare in this field\n3. Product Manager — customer success is one of the best on-ramps...",
    tags: ["career", "guidance", "professional-development"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create a personal fitness plan",
    prompt: "Act as a personal trainer. I will share my current fitness level, goals, and lifestyle, and your job is to design a workout plan tailored to me. Include exercise types, sets, reps, rest days, and progression.",
    whyItWorks: "Generic workout plans don't account for your specific situation. The AI adapts exercise selection, volume, and intensity based on your actual constraints.",
    exampleOutput: "**Your profile:** Beginner, 3 days/week available, home gym with dumbbells.\n\n**Week 1-4 Plan:**\nMon: Upper body (3x10 push-ups, 3x12 dumbbell rows...)\nWed: Lower body (3x12 goblet squats...)\nFri: Full body circuit...\n\n**Progression:** Add 1 rep per set each week.",
    tags: ["fitness", "health", "planning"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to help manage stress and anxiety",
    prompt: "Act as a mental health advisor. I will describe what I'm feeling, and you will suggest evidence-based strategies — cognitive behavioral techniques, meditation, mindfulness practices, or other therapeutic methods I can try.",
    whyItWorks: "Having immediate access to evidence-based coping strategies when you need them most can be genuinely helpful. The AI draws from established therapeutic frameworks.",
    exampleOutput: "**Technique: 5-4-3-2-1 Grounding**\nWhen anxiety spikes, name: 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste. This interrupts the spiral by forcing your brain into the present moment.\n\n**Reframe exercise:** Write down the anxious thought, then ask: 'What would I tell a friend who said this?'",
    tags: ["mental-health", "wellness", "self-care"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write an opinion piece",
    prompt: "Act as a columnist. I will give you a topic and you will write an opinion piece that provides insightful commentary. Use personal experience, back claims with evidence, and propose solutions. Make it engaging and persuasive.",
    whyItWorks: "Opinion writing requires a clear point of view, evidence, and persuasive structure. This prompt combines all three to produce publishable-quality commentary.",
    exampleOutput: "**Topic: Why every developer should write**\n\nThe best engineers I know are also the best writers. Not because writing is their hobby — but because clear writing forces clear thinking. When you can't explain your architecture in prose, you don't understand it yet...",
    tags: ["writing", "journalism", "opinion"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to run a text adventure game for you",
    prompt: "Act as a text-based adventure game. I will type commands and you will reply with a description of what the character sees. Only reply with the game output. Do not write explanations. My first command is: wake up.",
    whyItWorks: "Interactive fiction exercises creativity for both you and the AI. The constraint of responding only with game narrative creates an immersive, collaborative storytelling experience.",
    exampleOutput: "You open your eyes. A bare lightbulb swings above you, casting shadows across a concrete room. There's a heavy metal door to your NORTH and a cracked mirror on the EAST wall. Your pockets are empty. You hear footsteps somewhere above you.",
    tags: ["gaming", "interactive", "creative"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to find logical fallacies in any argument",
    prompt: "Act as a fallacy finder. I will give you statements or arguments and you will identify any logical errors, invalid reasoning, false assumptions, or incorrect conclusions. Provide evidence-based feedback for each one.",
    whyItWorks: "We all have blind spots in our reasoning. A systematic fallacy check catches errors in logic that sound convincing but don't hold up — like correlation-causation confusion or appeal to authority.",
    exampleOutput: "**Statement:** 'This diet worked for my friend, so it will work for everyone.'\n\n**Fallacy:** Hasty generalization + anecdotal evidence. One person's experience doesn't establish a pattern. Clinical studies with thousands of participants still show mixed results for most diets...",
    tags: ["critical-thinking", "logic", "analysis"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to question your beliefs with the Socratic method",
    prompt: "Act as Socrates. Use the Socratic method to question my beliefs. I will make a statement and you will keep questioning it to test my logic. Respond with one question at a time.",
    whyItWorks: "The Socratic method reveals unstated assumptions by following each claim to its logical conclusion. It's uncomfortable but incredibly effective for stress-testing ideas.",
    exampleOutput: "**You:** 'I think everyone should learn to code.'\n\n**Socrates:** 'What do you mean by \"everyone\"? Do you include a 75-year-old retired farmer?'\n\n**You:** 'Well, maybe not everyone, but most young people.'\n\n**Socrates:** 'Why young people specifically? What is it about code that you believe benefits them more than, say, learning a trade?'",
    tags: ["philosophy", "critical-thinking", "education"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to explain algorithms with ASCII visualizations",
    prompt: "Act as a computer science instructor. Explain [algorithm] to a beginner using Python code examples and ASCII art visualizations to show how the algorithm works step by step.",
    whyItWorks: "Visual representations of algorithms make abstract concepts concrete. Seeing the data change state at each step builds intuition that code alone can't.",
    exampleOutput: "**Bubble Sort — Step by Step:**\n\n[5, 3, 8, 1] → Compare 5,3 → swap\n[3, 5, 8, 1] → Compare 5,8 → no swap\n[3, 5, 8, 1] → Compare 8,1 → swap\n[3, 5, 1, 8] → Pass 1 complete. Largest (8) is now at end.",
    tags: ["programming", "education", "algorithms"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to simulate a SQL database",
    prompt: "Act as a SQL terminal. The database has tables: Products, Users, Orders, Suppliers. I will type queries and you will reply with the results in a table format inside a code block. Do not write explanations.",
    whyItWorks: "Practice SQL without setting up a database. The AI maintains consistent data across queries so you can practice joins, aggregations, and subqueries in a realistic flow.",
    exampleOutput: "```\nSELECT u.name, COUNT(o.id) as orders\nFROM Users u JOIN Orders o ON u.id = o.user_id\nGROUP BY u.name ORDER BY orders DESC LIMIT 3;\n\n| name          | orders |\n|---------------|--------|\n| Alice Chen    | 47     |\n| Bob Smith     | 31     |\n| Carol Davis   | 28     |\n```",
    tags: ["programming", "database", "simulation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to design a diet plan",
    prompt: "Act as a dietitian. Design a [vegetarian/vegan/etc.] meal plan for [number] people that has approximately [calories] per serving and a low glycemic index. Include nutritional breakdown.",
    whyItWorks: "Meal planning that accounts for calories, macros, dietary restrictions, and glycemic index is complex. The AI handles the math while you focus on what sounds appetizing.",
    exampleOutput: "**Lunch: Mediterranean Quinoa Bowl (480 cal)**\n- 1 cup cooked quinoa (220 cal, GI: 53)\n- ½ cup chickpeas (130 cal)\n- Cucumber, tomato, feta, olive oil dressing\n\n**Macros:** 18g protein, 52g carbs, 22g fat",
    tags: ["health", "nutrition", "cooking"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to brainstorm domain names",
    prompt: "Act as a domain name generator. I will describe my company or idea and you will suggest a list of domain name alternatives. Domains should be max 7-8 letters, short, unique — can be catchy or made-up words. Only reply with the list, no explanations.",
    whyItWorks: "Naming is one of the hardest creative challenges. The AI can generate hundreds of options in seconds, including neologisms and portmanteaus you'd never think of.",
    exampleOutput: "**Idea:** An app for sharing book highlights\n\nHighlit.com\nBookpulp.io\nMarginly.com\nQuotely.co\nHilight.app\nReadnote.io\nSpindle.co",
    tags: ["business", "naming", "startup"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write an in-depth tech review",
    prompt: "Act as a tech reviewer. I will give you a product name and you will write a thorough review covering pros, cons, key features, and comparisons to alternatives on the market.",
    whyItWorks: "A structured review framework ensures you consider every angle — performance, value, ecosystem, and alternatives — rather than just first impressions.",
    exampleOutput: "**Reviewing: Framework Laptop 16**\n\n**Pros:** Fully modular — swap GPU, ports, even keyboard. Right to repair done right.\n**Cons:** Battery life trails MacBook by ~3 hours. Heavier than competitors.\n**Verdict:** Best laptop for people who keep hardware 5+ years...",
    tags: ["technology", "reviews", "analysis"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write an academic research summary",
    prompt: "Act as an academic researcher. Research [topic] and present your findings as a structured paper: abstract, introduction, methodology, findings, and conclusion. Cite sources where possible.",
    whyItWorks: "Academic structure forces rigorous thinking. Even for non-academic topics, the abstract-methods-findings format produces clear, well-organized analysis.",
    exampleOutput: "**Abstract:** This paper examines the effectiveness of spaced repetition in language learning across 15 studies published between 2018-2024...\n\n**Key Finding:** Spaced repetition improved long-term retention by 47% compared to massed practice (p < 0.001)...",
    tags: ["academic", "research", "writing"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to design IT architecture for your app",
    prompt: "Act as an IT architect. I will describe my application's requirements and you will design the system architecture — including technology choices, data flow, API design, deployment strategy, and scaling considerations.",
    whyItWorks: "Architecture decisions made early have outsized impact. Getting a structured review of your approach surfaces scaling issues, single points of failure, and simpler alternatives.",
    exampleOutput: "**For your real-time chat app:**\n\n**Stack:** Next.js frontend → WebSocket gateway (Socket.io) → Redis pub/sub → PostgreSQL for persistence\n\n**Why not Firebase?** Your requirement for custom encryption rules out managed solutions...\n\n**Scaling plan:** Redis Cluster at 10K concurrent users, horizontal WebSocket servers behind a load balancer at 50K...",
    tags: ["technology", "architecture", "enterprise"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to review scientific papers",
    prompt: "Act as a journal reviewer. I will provide a paper or research summary and you will critically evaluate the research approach, methodology, conclusions, and offer constructive criticism on strengths and weaknesses.",
    whyItWorks: "Peer review is a skill that takes years to develop. The AI applies systematic evaluation criteria — methodology, sample size, statistical validity, conclusion strength — to any research.",
    exampleOutput: "**Strengths:** Clear hypothesis, appropriate sample size (n=2,400), longitudinal design.\n\n**Weaknesses:**\n1. Selection bias — participants were all from one university\n2. Self-reported data for the key dependent variable\n3. The p-value of 0.048 is borderline — would not survive correction for multiple comparisons...",
    tags: ["academic", "research", "peer-review"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to help with DIY home projects",
    prompt: "Act as a DIY expert. I will describe a home improvement project and you will create step-by-step instructions suitable for a beginner. Include tools needed, materials list, safety warnings, and estimated difficulty.",
    whyItWorks: "DIY projects fail when instructions assume too much knowledge. A beginner-focused guide with safety warnings and tool lists prevents costly mistakes.",
    exampleOutput: "**Project: Install floating shelves**\n\n**Difficulty:** Beginner | **Time:** 30 min\n\n**Tools:** Drill, level, stud finder, pencil, tape measure\n\n**Step 1:** Use stud finder to locate wall studs. Mark with pencil.\n⚠️ **Safety:** Always wear safety glasses when drilling...",
    tags: ["DIY", "home-improvement", "tutorials"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create a social media content strategy",
    prompt: "Act as a social media manager. Create a content strategy for [brand/product] including posting schedule, content pillars, engagement tactics, and metrics to track. Cover Instagram, Twitter/X, and LinkedIn.",
    whyItWorks: "Consistent social media requires a system, not just random posts. A content strategy with pillars and schedules turns social media from a chore into a repeatable process.",
    exampleOutput: "**Content Pillars:**\n1. Educational (40%) — Tips, how-tos, industry insights\n2. Behind-the-scenes (25%) — Team stories, process reveals\n3. Community (20%) — User spotlights, polls, Q&As\n4. Promotional (15%) — Product updates, launches\n\n**Schedule:** Mon/Wed/Fri on all platforms. LinkedIn gets longer-form on Tuesdays...",
    tags: ["social-media", "marketing", "strategy"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to coach your public speaking",
    prompt: "Act as a public speaking coach. Help me improve my presentation skills. Give me techniques for clear delivery, body language, voice modulation, and audience engagement. Critique my speech outline if I share one.",
    whyItWorks: "Public speaking anxiety often comes from lack of preparation, not lack of talent. Structured coaching on delivery techniques builds confidence through competence.",
    exampleOutput: "**Rule of Three:** Structure your talk around 3 key points. Audiences remember 3 things, not 7.\n\n**The Pause:** After a key statement, pause for 2 full seconds. It feels long to you but signals confidence to the audience.\n\n**Open with a question:** 'How many of you have...' gets heads nodding and engagement up immediately.",
    tags: ["public-speaking", "communication", "presentation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create data visualizations in text",
    prompt: "Act as a data visualization expert. I will share data and you will suggest the best chart type to represent it, then create a text-based or ASCII visualization. Explain why you chose that format.",
    whyItWorks: "Choosing the wrong chart type obscures your data story. The AI matches your data shape to the right visualization and explains the reasoning, teaching you visualization principles.",
    exampleOutput: "**Your data:** Monthly revenue for 12 months\n\n**Best format:** Line chart (shows trend over time)\n\n```\nRevenue ($K)\n50 |          ╱‾‾\n40 |     ╱‾‾╱\n30 |  ╱‾╱\n20 |╱╱\n   +----------→\n   J F M A M J\n```\n**Insight:** Clear upward trend with acceleration in Q2.",
    tags: ["data-science", "visualization", "analysis"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to research any historical event in depth",
    prompt: "Act as a historian. Research [event/period] and analyze the cultural, economic, political, and social context. Use primary sources where possible and explain how this event shaped what came after.",
    whyItWorks: "History is about connections, not just dates. Analyzing events through multiple lenses (cultural, economic, political) reveals patterns and lessons applicable to today.",
    exampleOutput: "**Event: The 1918 Spanish Flu**\n\n**Economic impact:** GDP dropped 6-8% in affected countries. But the recovery was remarkably fast — a 'V-shaped' rebound by 1920.\n\n**Social impact:** Paradoxically, it accelerated public health infrastructure. Cities that locked down earliest recovered fastest economically...",
    tags: ["history", "research", "education"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write a persuasive essay on any topic",
    prompt: "Act as an essay writer. Write a persuasive essay on [topic]. Start with a compelling hook, build your argument with evidence, address counterarguments, and end with a strong call to action.",
    whyItWorks: "Persuasive writing follows a proven structure: hook, claim, evidence, counterargument, resolution. This prompt ensures all elements are present and properly ordered.",
    exampleOutput: "**Hook:** Every 40 seconds, someone in America has a stroke. Most of them didn't know they were at risk.\n\n**Claim:** Universal preventive health screenings would save 100,000 lives annually...\n\n**Counterargument:** Critics cite cost, but the math is clear: prevention costs $1 for every $7 spent on treatment...",
    tags: ["writing", "academic", "persuasion"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create ASCII art of anything",
    prompt: "Act as an ASCII artist. I will name an object and you will create it as ASCII art inside a code block. Only output the ASCII art, no explanations.",
    whyItWorks: "ASCII art adds personality to documentation, README files, and terminal apps. The constraint of using only text characters forces creative spatial thinking.",
    exampleOutput: "```\n    /\\_/\\\n   ( o.o )\n    > ^ <\n   /|   |\\\n  (_|   |_)\n```",
    tags: ["art", "ASCII", "creative"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to generate regex patterns for you",
    prompt: "Act as a regex generator. I will describe a text pattern I want to match and you will generate the regular expression for it. Only reply with the regex — no explanations. Then I'll ask if I need a breakdown.",
    whyItWorks: "Regex is notoriously hard to write from scratch. Describing what you want in plain English and getting the pattern back saves time and reduces errors.",
    exampleOutput: "**Request:** Match email addresses\n\n`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$`\n\n**Request:** Match US phone numbers in any format\n\n`^\\+?1?[-.\\s]?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$`",
    tags: ["programming", "regex", "tools"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to interpret your dreams",
    prompt: "Act as a dream interpreter. I will describe a dream and you will provide interpretations based on the symbols and themes present. Do not make personal assumptions about the dreamer — focus on universal symbolism.",
    whyItWorks: "Dream interpretation through symbolic analysis can reveal subconscious patterns and anxieties. Even if you're skeptical, it's a useful framework for self-reflection.",
    exampleOutput: "**Dream:** I was flying over a city but my shoes kept falling off.\n\n**Interpretation:** Flying typically represents freedom or ambition — you may be experiencing a sense of rising above challenges. Losing shoes suggests anxiety about being unprepared or exposed. The combination might reflect excitement about a new opportunity paired with imposter syndrome...",
    tags: ["psychology", "dreams", "interpretation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to generate a complete startup business plan",
    prompt: "I have an idea: [idea]. Generate a business plan including: idea name, one-liner, target user persona, pain points solved, value propositions, sales channels, revenue streams, cost structure, key activities, key resources, key partners, validation steps, year 1 cost estimate, and potential challenges. Format as a markdown table.",
    whyItWorks: "The Business Model Canvas framework forces you to think through every aspect of a business systematically. Getting a first draft in minutes lets you iterate instead of staring at a blank page.",
    exampleOutput: "| Component | Detail |\n|-----------|--------|\n| **Name** | ReadFlow |\n| **One-liner** | Curated reading lists that adapt to your interests |\n| **Target User** | Knowledge workers who want to read more but feel overwhelmed |\n| **Revenue** | Freemium: free for 3 lists, $8/mo for unlimited + analytics |",
    tags: ["startup", "business", "entrepreneurship"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to review your code like a senior developer",
    prompt: "Act as a senior code reviewer. I will share my code and you will review it for bugs, performance issues, security vulnerabilities, readability, and best practices. Explain the reasoning behind each suggestion and offer alternative approaches.",
    whyItWorks: "Code review from an experienced perspective catches issues you can't see in your own code — from subtle bugs to architectural concerns. The explanations teach you to spot these patterns yourself.",
    exampleOutput: "**Line 12:** `user.password === input` — comparing passwords in plaintext. Use bcrypt.compare() instead.\n\n**Line 27:** N+1 query inside a loop. This will make 100 DB calls for 100 users. Use a single query with WHERE IN.\n\n**Line 45:** Catching all errors silently (`catch {}`) — this hides bugs. At minimum, log the error.",
    tags: ["programming", "code-review", "best-practices"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to generate conventional commit messages",
    prompt: "Act as a commit message generator following the Conventional Commits specification. I will describe my changes (or paste a diff) and you will generate a properly formatted commit message with type, optional scope, and description.",
    whyItWorks: "Consistent commit messages make git history readable and enable automated changelogs. The Conventional Commits format is a widely-adopted standard that the AI can apply perfectly.",
    exampleOutput: "**Changes:** Added user authentication with JWT tokens and a login page.\n\n```\nfeat(auth): add JWT-based user authentication\n\n- Add login/register API endpoints\n- Implement JWT token generation and validation\n- Create login page with form validation\n- Add auth middleware for protected routes\n```",
    tags: ["git", "programming", "productivity"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to audit your website's accessibility",
    prompt: "Act as an accessibility auditor. I will describe my website or share its HTML, and you will review it for WCAG 2.2 compliance — focusing on keyboard navigation, screen reader compatibility, color contrast, and semantic HTML.",
    whyItWorks: "Accessibility issues are easy to miss if you're not a screen reader user. A systematic WCAG audit catches issues that affect real users and can also have legal implications.",
    exampleOutput: "**Issues found:**\n\n1. **Critical:** Images missing alt text (WCAG 1.1.1)\n2. **Serious:** Color contrast ratio 2.8:1 on muted text — needs 4.5:1 minimum (WCAG 1.4.3)\n3. **Moderate:** No skip-to-content link for keyboard users\n4. **Minor:** Links say 'click here' instead of describing the destination",
    tags: ["accessibility", "web-development", "compliance"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to generate a product requirements document",
    prompt: "Act as a product manager. I will describe a product idea and you will write a PRD with these sections: Subject, Introduction, Problem Statement, Goals and Objectives, User Stories, Technical Requirements, Benefits, KPIs, Development Risks, and Conclusion.",
    whyItWorks: "A PRD forces you to think through every dimension of a product before building. Having a structured first draft lets you focus on refining ideas rather than formatting.",
    exampleOutput: "**Subject:** TaskFlow — AI-Powered Task Prioritization\n\n**Problem:** Knowledge workers spend 2.5 hours daily deciding what to work on. Current tools list tasks but don't prioritize them.\n\n**User Story:** As a busy PM, I want my task list automatically prioritized by impact and deadline so I can start my day without decision fatigue...",
    tags: ["product", "planning", "documentation"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to recommend songs similar to any song",
    prompt: "I will give you a song and you will create a playlist of 10 similar songs. Provide a playlist name and description. Do not choose songs by the same artist.",
    whyItWorks: "Music discovery algorithms are great but opaque. Asking AI to explain why songs are similar gives you insight into musical patterns and helps you articulate your taste.",
    exampleOutput: "**Song:** 'Midnight City' by M83\n\n**Playlist:** 'Neon Nostalgia'\n**Description:** Synth-driven tracks that feel like driving through a city at night.\n\n1. 'Somebody Else' — The 1975\n2. 'Digital Love' — Daft Punk\n3. 'Electric Feel' — MGMT\n4. 'Heart It Races' — Architecture in Helsinki...",
    tags: ["music", "recommendations", "entertainment"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to proofread with surgical precision",
    prompt: "Act as a proofreader. I will give you text and you will review it for spelling, grammar, and punctuation errors only. Do not rephrase or change style — just fix errors and explain each correction.",
    whyItWorks: "Proofreading is different from editing. This prompt constrains the AI to only fix objective errors, preserving your voice while catching the mistakes your eyes skip over.",
    exampleOutput: "**Original:** 'Their going to the store tommorrow, they should of called ahead.'\n\n**Corrected:** 'They're going to the store tomorrow, they should have called ahead.'\n\n**Fixes:** their→they're (contraction), tommorrow→tomorrow (spelling), should of→should have (grammar)",
    tags: ["writing", "editing", "grammar"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to be a Wikipedia-style knowledge base",
    prompt: "Act as a Wikipedia page. I will give you a topic and you will provide a summary in Wikipedia's style: introductory paragraph overview, then organized sections covering history, key concepts, significance, and related topics.",
    whyItWorks: "Wikipedia's format is optimized for learning: overview first, then progressive detail. This structure works for any topic and ensures comprehensive coverage.",
    exampleOutput: "**Topic: Spaced Repetition**\n\n**Spaced repetition** is an evidence-based learning technique that incorporates increasing intervals of time between subsequent review of previously learned material to exploit the psychological spacing effect...\n\n**History:** First proposed by Cecil Alec Mace in 1932...\n\n**How it works:** ...",
    tags: ["research", "knowledge", "reference"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to design your room's interior",
    prompt: "Act as an interior decorator. Tell me what theme, color scheme, furniture placement, and decorative options to use for my [room type] to enhance aesthetics and comfort. My budget is [budget] and my style preference is [style].",
    whyItWorks: "Interior design requires balancing aesthetics, function, budget, and personal taste. The AI considers all constraints simultaneously and suggests cohesive design systems rather than random items.",
    exampleOutput: "**Room:** Living room, 15x12 ft, $2K budget, minimalist style\n\n**Color scheme:** White walls + warm wood + one sage green accent wall\n\n**Key pieces:**\n- Low-profile sofa in light gray ($600) — face toward window\n- Round walnut coffee table ($200) — breaks up angular furniture\n- Floor lamp with warm bulb ($80) — no overhead lighting, creates coziness...",
    tags: ["interior-design", "home", "lifestyle"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to suggest creative hobbies and activities",
    prompt: "I'm looking for a new hobby or activity. I enjoy [interests], have [time available] per week, and my budget is [budget]. Suggest 5 options I might not have considered, with a description of why each might appeal to me.",
    whyItWorks: "We default to hobbies we already know about. The AI can connect your preferences to activities you've never encountered, expanding your possibilities.",
    exampleOutput: "**Based on:** You like puzzles, have 3 hours/week, low budget.\n\n1. **Geocaching** — Real-world treasure hunts using GPS. Free app, gets you outdoors, satisfies the puzzle itch.\n2. **Bookbinding** — Making your own journals/notebooks. Starter kit: $30. Meditative and produces beautiful results.\n3. **Lock sport** — Learning to pick locks (legally). Practice locks: $20. Mechanical puzzles you can hold...",
    tags: ["hobbies", "lifestyle", "creativity"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to generate teaching worksheets",
    prompt: "Act as a worksheet generator. Create a [subject] worksheet for [level] students with [number] questions. Include fill-in-the-blank, multiple choice, and short answer formats. Provide an answer key.",
    whyItWorks: "Creating worksheets is time-consuming for teachers. The AI generates varied question types at the right difficulty level, complete with answer keys.",
    exampleOutput: "**English Grammar Worksheet — Intermediate**\n\n**Fill in the blank:**\n1. She ___ (go) to the store yesterday. → went\n2. They ___ (be) studying for three hours. → have been\n\n**Multiple choice:**\n3. Which is correct?\na) He don't like coffee ❌\nb) He doesn't like coffee ✅",
    tags: ["education", "teaching", "worksheets"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to generate secure passwords with specific rules",
    prompt: "Generate [number] secure passwords with these requirements: [length] characters, must include uppercase, lowercase, numbers, and special characters. Make them pronounceable enough to be memorable. Only output the passwords.",
    whyItWorks: "Good passwords balance security and memorability. The AI can generate passwords that meet strict requirements while still having phonetic patterns that aid recall.",
    exampleOutput: "1. Kx9#mLpw2$Vn\n2. Rj4!bTqe7@Ws\n3. Fm6&yNhc3*Dp\n4. Qz8%aGks5^Lt\n5. Wv2!eJnr9$Bx",
    tags: ["security", "tools", "productivity"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to generate article titles that get clicks",
    prompt: "Act as a headline generator. I will give you my article's topic and key points, and you will generate 10 attention-grabbing titles. Keep them under 15 words. Mix formats: questions, numbers, how-tos, and bold statements.",
    whyItWorks: "Headlines determine whether anyone reads your content. Having 10 options with different formats lets you A/B test or pick the one that best matches your audience.",
    exampleOutput: "**Topic:** Why remote work is here to stay\n\n1. Remote Work Won. Here's the Data.\n2. 7 Stats That Prove the Office Is Never Coming Back\n3. Why Your Best Employees Will Quit If You Mandate Return-to-Office\n4. The Remote Work Debate Is Over (And the Numbers Are Clear)\n5. Still Forcing People Back to the Office? Read This First.",
    tags: ["writing", "content", "titles"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to help you negotiate salary",
    prompt: "Act as a negotiation coach. I have a job offer for [role] at [company] offering [salary]. The market rate is [market rate]. Help me draft a counter-offer email that is professional, backed by data, and leaves room for discussion.",
    whyItWorks: "Salary negotiation is uncomfortable for most people. Having a coach draft the actual email with data-backed justification removes the emotional barrier and produces better outcomes.",
    exampleOutput: "**Subject:** Excited About the Offer — A Few Thoughts\n\n'Thank you for the offer — I'm genuinely excited about the role. Based on my research of market rates for this position in [city] (Glassdoor, Levels.fyi), and given my [X years] of experience with [specific skill], I'd like to propose a base salary of...'",
    tags: ["career", "negotiation", "communication"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to explain a codebase you just inherited",
    prompt: "I just inherited a codebase I don't understand. Here is [file/code]. Explain what this code does at a high level, identify the main patterns and design decisions, and flag anything that looks unusual or concerning.",
    whyItWorks: "Understanding unfamiliar code is one of the hardest parts of software engineering. A high-level walkthrough that explains patterns and flags concerns accelerates onboarding dramatically.",
    exampleOutput: "**Overview:** This is a React app using the Repository pattern with a Redux store.\n\n**Key patterns:**\n- Data fetching happens in `/services/` using Axios interceptors for auth\n- State management splits 'server state' (React Query) from 'UI state' (Redux)\n\n**Concerns:**\n- `utils/helpers.ts` is 800 lines — likely a dumping ground that needs refactoring\n- No error boundaries anywhere — one bad component crashes the whole app",
    tags: ["programming", "onboarding", "code-review"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write a cold email that gets replies",
    prompt: "Write a cold email to [person/role] about [purpose]. Keep it under 100 words. Personalize the opening, state a clear value proposition, and end with a low-friction ask. No generic flattery.",
    whyItWorks: "Cold emails fail when they're too long, too generic, or ask too much. The constraints force a punchy, personalized message with a clear reason to reply.",
    exampleOutput: "**Subject:** Quick question about your auth system\n\nHi Sarah,\n\nI noticed your team open-sourced your rate limiter last month — really elegant approach to the sliding window problem.\n\nWe built something similar for API auth and found a way to cut false positives by 60%. Would a 15-minute call be worth your time to compare approaches?\n\nNo pitch, just two engineers geeking out.\n\n— Alex",
    tags: ["communication", "sales", "email"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create a lesson plan on any topic",
    prompt: "Act as an educational content creator. Create a 1-hour lesson plan on [topic] for [audience level]. Include learning objectives, activities, discussion questions, and a way to assess understanding.",
    whyItWorks: "Effective teaching requires structure, not just knowledge. A lesson plan with objectives, activities, and assessment ensures your audience actually learns, not just listens.",
    exampleOutput: "**Topic:** Intro to Design Thinking | **Audience:** College students\n\n**Objectives:** Define the 5 stages, apply empathy mapping, prototype one solution.\n\n**0-10 min:** Hook — show a badly designed product. Ask: 'What would you fix?'\n**10-25 min:** Explain the 5 stages with real examples\n**25-45 min:** Activity — students empathy-map a problem in pairs\n**45-55 min:** Share solutions, vote on most creative\n**55-60 min:** Reflection prompt...",
    tags: ["education", "content-creation", "teaching"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to practice a sales conversation with you",
    prompt: "Act as a potential customer for [product]. I am the salesperson. Be skeptical but fair — ask tough questions, raise objections, and only be convinced by genuine value. Start by saying: 'So, what are you selling?'",
    whyItWorks: "Sales skills improve through practice against realistic resistance. The AI creates a safe space to rehearse pitches, handle objections, and refine your value proposition.",
    exampleOutput: "**Customer:** So, what are you selling?\n\n*[You pitch]*\n\n**Customer:** Interesting, but we already use [competitor]. What makes yours different?\n\n*[You respond]*\n\n**Customer:** That sounds great in theory, but I've been burned by tools that promise AI magic. Can you show me a concrete example?",
    tags: ["sales", "business", "roleplay"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to plan your event logistics",
    prompt: "Act as an event planner. I am organizing [event type] for [number] people at [location]. Help me plan logistics: venue setup, catering, schedule, transportation, safety considerations, and contingency plans.",
    whyItWorks: "Event planning has dozens of interdependent details that are easy to forget. A comprehensive logistics plan surfaces everything from parking to dietary restrictions before the day arrives.",
    exampleOutput: "**Event:** Team offsite, 40 people, 2 days, mountain lodge\n\n**Pre-event:** Dietary survey (send 2 weeks before), transportation signup sheet\n\n**Day 1 Schedule:**\n9:00 — Arrival + coffee\n9:30 — Icebreaker (not the cringe kind: 'Two truths and a lie' works)\n10:00 — Strategy session 1...\n\n**Contingency:** Rain plan for outdoor activities → move to conference room B. Backup catering contact...",
    tags: ["events", "planning", "logistics"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to help with financial planning and budgeting",
    prompt: "Act as a financial advisor. I will share my income, expenses, and financial goals, and you will create a budget plan, suggest investment strategies considering my risk tolerance, and identify areas where I can cut costs.",
    whyItWorks: "Most people don't budget because it feels overwhelming. Having someone structure the numbers, categorize spending, and identify obvious savings makes it actionable.",
    exampleOutput: "**Income:** $6,000/mo after tax\n\n**Recommended split (50/30/20):**\n- Needs: $3,000 (rent $1,800, groceries $400, insurance $200...)\n- Wants: $1,800 (dining, entertainment, subscriptions)\n- Save/Invest: $1,200\n\n**Quick wins:** Your 5 streaming subscriptions cost $75/mo. You watch 2 of them. Save $45/mo = $540/year...",
    tags: ["finance", "budgeting", "planning"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to troubleshoot your car problems",
    prompt: "Act as an auto mechanic. I will describe symptoms my car is showing and you will diagnose possible causes, explain what each issue means, estimate repair urgency (drive now vs. fix immediately), and suggest whether I can DIY or need a shop.",
    whyItWorks: "Knowing whether a car issue is urgent prevents both dangerous driving and unnecessary panic. Understanding the diagnosis helps you avoid being overcharged at the shop.",
    exampleOutput: "**Symptom:** Squealing noise when braking, gets worse downhill.\n\n**Likely cause:** Brake pad wear indicators — the metal tab is touching the rotor.\n\n**Urgency:** Fix within 1-2 weeks. Safe to drive short distances now, but metal-on-metal will damage rotors ($$).\n\n**DIY?** Yes, if you have basic tools. Pads cost $30-50. Shop would charge $150-300.",
    tags: ["automotive", "troubleshooting", "DIY"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to plan your investment strategy",
    prompt: "Act as an investment advisor. Given my age ([age]), risk tolerance ([low/medium/high]), current savings ($[amount]), and monthly investment budget ($[amount]), suggest a diversified portfolio allocation with specific fund types and reasoning.",
    whyItWorks: "Investment advice is often generic. Providing your specific numbers and risk profile lets the AI suggest a concrete allocation rather than vague principles.",
    exampleOutput: "**Profile:** Age 30, medium risk, $50K saved, $500/mo to invest\n\n**Suggested allocation:**\n- 60% US Total Stock Market Index (e.g., VTI)\n- 20% International Index (e.g., VXUS)\n- 10% Bond Index (e.g., BND)\n- 10% REIT Index (e.g., VNQ)\n\n**Why:** At 30, you have 35 years of compounding. Heavy equity weighting is appropriate because you can ride out volatility...",
    tags: ["investment", "finance", "strategy"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to suggest healthy meals that are quick and cheap",
    prompt: "Suggest 5 meals that are nutritionally balanced, take under 30 minutes to prepare, and cost under $5 per serving. Include ingredients, rough calorie count, and prep instructions.",
    whyItWorks: "The three biggest barriers to healthy eating are time, cost, and knowledge. This prompt optimizes for all three simultaneously.",
    exampleOutput: "**1. Black Bean Quesadilla (420 cal, $2.50, 10 min)**\nTortilla + canned black beans + shredded cheese + salsa. Pan-fry until crispy. Add frozen spinach for bonus nutrition.\n\n**2. Egg Fried Rice (380 cal, $1.80, 15 min)**\nLeftover rice + 2 eggs + frozen mixed veggies + soy sauce. Day-old rice fries best...",
    tags: ["cooking", "health", "budget"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write a motivational speech",
    prompt: "Write a 5-minute motivational speech about [topic] for [audience]. Start with a story, build to an emotional peak, and end with a specific call to action. Make it sound natural, not preachy.",
    whyItWorks: "Great speeches follow a structure: story → lesson → call to action. The 'not preachy' instruction keeps the tone authentic rather than overwrought.",
    exampleOutput: "Three years ago, I almost quit. Not dramatically — no letter of resignation. I just... stopped trying. I showed up, did the minimum, went home...\n\n*[builds to turning point]*\n\n...The difference between where you are and where you want to be isn't talent. It's one more try after you think you're done.\n\nSo here's what I'm asking: this week, do the one thing you've been avoiding. Just one. Start there.",
    tags: ["motivation", "public-speaking", "writing"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to help you write a cover letter that stands out",
    prompt: "Write a cover letter for [role] at [company]. My key qualifications are [list]. Don't be generic — reference something specific about the company and connect it to my experience. Keep it under 250 words.",
    whyItWorks: "Generic cover letters get ignored. Connecting your specific experience to the company's specific situation shows you've done your homework and can articulate fit.",
    exampleOutput: "I noticed [Company] just launched its API marketplace — I've spent the last 3 years building exactly this kind of developer platform at [Previous Company], growing it from 50 to 2,000 active integrations.\n\nWhat excites me about this role isn't just the tech. It's that you're betting on developers as your growth channel...",
    tags: ["career", "writing", "job-search"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create a study schedule for any exam",
    prompt: "I have [exam] in [timeframe]. The topics are [list topics]. Create a daily study schedule that uses spaced repetition, mixes topics to avoid fatigue, and includes review sessions. Mark which topics need the most time.",
    whyItWorks: "Effective studying isn't about hours — it's about structure. Spaced repetition, interleaving, and scheduled review are evidence-based techniques that the AI can plan optimally.",
    exampleOutput: "**Exam:** AWS Solutions Architect in 4 weeks\n\n**Week 1 Focus:** Foundations (EC2, S3, VPC)\nMon: EC2 (2hr) — new material\nTue: S3 (2hr) — new material\nWed: EC2 review (30min) + VPC (2hr)\nThu: S3 review (30min) + Practice questions\nFri: All three — practice exam\n\n**Priority:** VPC and IAM need extra time (most exam questions)...",
    tags: ["education", "productivity", "planning"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to explain complex legal concepts simply",
    prompt: "Act as a legal educator. Explain [legal concept/situation] in plain English that a non-lawyer can understand. Include practical implications — what does this actually mean for a regular person?",
    whyItWorks: "Legal language is deliberately precise but practically incomprehensible. Translating to plain English with real-world implications makes the law accessible and actionable.",
    exampleOutput: "**Concept: Non-compete agreements**\n\n**Plain English:** Your employer is saying 'After you leave, you can't work for a competitor for X months within Y miles.'\n\n**Practical reality:** These are increasingly unenforceable in many states. California bans them entirely. Even where they're legal, most companies won't spend $50K suing an individual employee...\n\n**What to do:** Don't refuse to sign (it might cost you the job), but know your state's rules.",
    tags: ["legal", "education", "advice"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create a project retrospective",
    prompt: "Act as a facilitator. Help me run a project retrospective for [project]. Structure it as: What went well? What didn't? What did we learn? What should we do differently next time? Draw out specific, actionable insights.",
    whyItWorks: "Retrospectives are only valuable if they produce specific takeaways. The structured format ensures you capture both successes to repeat and failures to prevent.",
    exampleOutput: "**What went well:**\n- Shipped 2 days early by cutting scope to MVP\n- Daily standups kept everyone aligned\n\n**What didn't:**\n- Testing was squeezed into the last 3 days — found 2 critical bugs\n- Stakeholder feedback came too late to incorporate\n\n**Action items:**\n1. Allocate 20% of timeline to testing from day 1\n2. Schedule stakeholder review at 50% completion, not 90%",
    tags: ["project-management", "teamwork", "process"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write an email you're dreading",
    prompt: "I need to send a difficult email about [situation]. The recipient is [relationship]. I want to be [direct/diplomatic/firm]. Help me write it so I'm clear about [outcome I want] without damaging the relationship.",
    whyItWorks: "Difficult emails get procrastinated because we can't find the right tone. Having someone else draft it first breaks the paralysis and gives you something to edit rather than create from scratch.",
    exampleOutput: "**Situation:** Telling a client the project will be 2 weeks late.\n\nSubject: Project timeline update — revised delivery date\n\nHi [Name],\n\nI want to be upfront: we're going to need two additional weeks to deliver [project]. Here's why, and here's what we're doing about it.\n\n[Reason — honest, not excuse-making]\n\nThe new delivery date is [date]. To make up for the delay, we're [concrete offering]...",
    tags: ["communication", "email", "professional"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to generate user interview questions",
    prompt: "I'm building [product] for [audience]. Generate 15 user interview questions that uncover real pain points, current workarounds, and willingness to pay. Avoid leading questions. Mix open-ended and specific.",
    whyItWorks: "Bad interview questions confirm what you already believe. Good questions uncover what you don't know. This prompt generates non-leading questions that reveal genuine user behavior.",
    exampleOutput: "1. Walk me through the last time you had to [task]. What was that like?\n2. What tools do you currently use for this? What's frustrating about them?\n3. If this problem magically disappeared tomorrow, what would change about your work?\n4. Have you tried to solve this before? What happened?\n5. How much time do you spend on this per week?...",
    tags: ["product", "research", "user-interviews"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write release notes users will actually read",
    prompt: "I'm shipping [features/fixes]. Write release notes that are clear, concise, and user-focused. Lead with the benefit, not the feature. Group by impact. Skip internal/technical changes users don't care about.",
    whyItWorks: "Most release notes are written for developers, not users. Leading with benefits ('You can now X') instead of features ('Added support for Y') makes users care.",
    exampleOutput: "## What's New in v2.4\n\n**Big improvements:**\n- **Find anything instantly** — Search now works across all your projects, not just the current one\n- **No more lost work** — Auto-save kicks in every 30 seconds (was 5 minutes)\n\n**Small but nice:**\n- Dark mode now applies to the editor toolbar (finally)\n- Export to PDF includes images (previously text-only)",
    tags: ["product", "writing", "communication"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create a competitive analysis",
    prompt: "Act as a business analyst. I'm building [product]. My competitors are [list]. Create a competitive analysis comparing features, pricing, target audience, strengths, and weaknesses. Identify gaps I can exploit.",
    whyItWorks: "Competitive analysis reveals market gaps and positioning opportunities. A structured comparison across multiple dimensions helps you find where competitors are weak and where you can differentiate.",
    exampleOutput: "| Feature | You | Competitor A | Competitor B |\n|---------|-----|-------------|-------------|\n| Real-time collab | Yes | No | Yes |\n| Free tier | 3 projects | 1 project | None |\n\n**Gap opportunity:** None of them offer async collaboration with video — this is a whitespace you could own...",
    tags: ["business", "strategy", "analysis"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to explain a concept using only simple words",
    prompt: "Explain [complex concept] using only the 1,000 most common English words. If you need a technical term, define it using simple words first.",
    whyItWorks: "Restricting vocabulary forces truly simple explanations. If you can't explain it in common words, you don't fully understand it — this prompt tests that.",
    exampleOutput: "**Concept: Encryption**\n\nImagine you write a letter but change every letter to a different one using a secret plan. Only the person who knows your plan can read the letter. If someone else finds it, they just see a mess of letters that means nothing. That's what computers do with your messages and money information to keep it safe.",
    tags: ["explanation", "simplification", "education"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to help you set up OKRs",
    prompt: "Help me write OKRs for [team/project] this quarter. Each objective should be ambitious but achievable. Key results should be measurable with specific numbers. Include 3 objectives with 3 key results each.",
    whyItWorks: "OKRs fail when objectives are vague or key results aren't measurable. The AI enforces the structure — ambitious objectives + specific numbers — that makes OKRs effective.",
    exampleOutput: "**Objective 1:** Become the go-to tool for developer onboarding\n- KR1: Increase new user activation rate from 34% to 55%\n- KR2: Reduce time-to-first-value from 45 min to under 15 min\n- KR3: Achieve NPS of 50+ among users in their first week\n\n**Objective 2:** Build a self-sustaining community...",
    tags: ["planning", "goals", "management"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to convert a meeting into action items",
    prompt: "Here are my meeting notes: [paste notes]. Extract every action item, assign an owner if mentioned, set a due date if discussed, and flag any unresolved decisions that need follow-up.",
    whyItWorks: "Most meetings generate ideas but not accountability. Extracting action items with owners and dates converts vague discussion into concrete next steps.",
    exampleOutput: "**Action items:**\n1. [ ] Sarah: Send revised pricing proposal to client → by Friday\n2. [ ] Dev team: Fix checkout bug (critical) → by EOD Wednesday\n3. [ ] Alex: Schedule user research sessions → by next Monday\n\n**Unresolved decisions:**\n- Do we launch V2 before or after the conference? (Need VP input)\n- Pricing tier structure — revisit Thursday",
    tags: ["productivity", "meetings", "organization"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to write documentation that developers will read",
    prompt: "Write technical documentation for [feature/API/tool]. Start with a 2-sentence summary, then show a working code example before explaining the details. Use the format: summary → quick start → full reference.",
    whyItWorks: "Developers don't read docs top-to-bottom. They want: what is this, how do I use it, where are the details. The summary → example → reference format matches how developers actually consume documentation.",
    exampleOutput: "## Rate Limiter\n\nLimits API requests per user to prevent abuse. Drop-in middleware for Express.\n\n**Quick start:**\n```js\nimport { rateLimit } from './middleware';\napp.use(rateLimit({ window: '15m', max: 100 }));\n```\n\n**That's it.** For custom rules, read on...\n\n**Options:**\n- `window` — Time window (default: '15m')\n- `max` — Max requests per window (default: 100)...",
    tags: ["technical-writing", "documentation", "programming"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to debug your code by describing the symptoms",
    prompt: "My code is supposed to [expected behavior] but instead it [actual behavior]. Here is the code: [paste code]. Find the bug, explain why it's happening, and show me the fix.",
    whyItWorks: "Describing expected vs. actual behavior is the foundation of debugging. The AI reads your code with fresh eyes, unclouded by the assumptions that caused the bug.",
    exampleOutput: "**Bug found on line 12:**\n```js\n// You wrote:\nif (user.role = 'admin')\n// Should be:\nif (user.role === 'admin')\n```\n\n**Why:** Single `=` is assignment, not comparison. This always evaluates to truthy, so every user gets admin access. Use `===` for strict comparison.",
    tags: ["programming", "debugging", "problem-solving"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create a brand voice guide",
    prompt: "Help me define a brand voice for [brand/product]. Include: personality traits (3-5 adjectives), tone guidelines, do's and don'ts, example sentences showing the voice in action, and words to avoid.",
    whyItWorks: "Consistent brand voice builds trust and recognition. A concrete guide with examples — not just adjectives — ensures everyone on the team writes in the same voice.",
    exampleOutput: "**Brand personality:** Confident, warm, slightly nerdy\n\n**We say:** 'Here's what we found' (direct)\n**We don't say:** 'We are pleased to inform you' (corporate)\n\n**Do:** Use contractions, be specific, use analogies\n**Don't:** Use jargon, hedge with 'perhaps', use exclamation marks\n\n**Words to avoid:** leverage, synergy, disrupt, game-changing",
    tags: ["branding", "writing", "marketing"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to create an onboarding checklist for new hires",
    prompt: "Create a 30-day onboarding checklist for a new [role] at a [company type]. Include day 1, week 1, week 2-3, and month 1 milestones. Cover logistics, team introductions, learning goals, and first deliverables.",
    whyItWorks: "Bad onboarding loses employees. A structured 30-day plan with clear milestones helps new hires feel supported and productive rather than lost and overwhelmed.",
    exampleOutput: "**Day 1:**\n- [ ] Laptop and accounts set up before arrival\n- [ ] Welcome lunch with direct team\n- [ ] 1:1 with manager: 30-day expectations\n\n**Week 1:**\n- [ ] Shadow 3 customer calls\n- [ ] Read product docs + complete internal course\n- [ ] Coffee chats with 5 cross-functional teammates\n\n**Week 2-3:**\n- [ ] First small project (low-stakes, real impact)\n- [ ] Present findings to team...",
    tags: ["management", "onboarding", "HR"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to help you prepare for a tough conversation",
    prompt: "I need to have a difficult conversation with [person/role] about [topic]. Help me prepare: what are the key points I need to make, what objections should I expect, and how should I frame this to be productive rather than confrontational?",
    whyItWorks: "Difficult conversations go wrong when we're reactive instead of prepared. Anticipating objections and framing the discussion around shared goals transforms confrontation into collaboration.",
    exampleOutput: "**Key points (lead with these):**\n1. Start with shared goal: 'We both want this project to succeed'\n2. Specific observation: 'The last 3 deadlines were missed by 4+ days'\n3. Impact: 'This caused [specific consequence]'\n\n**Likely objections:**\n- 'The requirements kept changing' → Acknowledge this is real, then redirect to process\n- 'I was waiting on other teams' → Ask what would help unblock faster\n\n**Frame:** This is about the process, not the person.",
    tags: ["communication", "leadership", "professional"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to turn your notes into a structured document",
    prompt: "Here are my messy notes from [meeting/research/brainstorm]: [paste notes]. Organize them into a clear, structured document with headings, grouped themes, and highlighted key decisions or action items.",
    whyItWorks: "Raw notes capture everything but organize nothing. Having the AI identify themes, group related ideas, and extract decisions turns chaos into clarity.",
    exampleOutput: "**Organized from your brainstorm notes:**\n\n## Product Direction\n- Consensus: Focus on B2B before B2C\n- Key insight: Enterprise customers want self-hosted option\n\n## Technical Decisions\n- Use PostgreSQL (not MongoDB) — relational data is a better fit\n- Deploy on AWS (team has existing experience)\n\n## Open Questions\n- Pricing model still undecided (subscription vs. usage-based)\n- Need legal review of data processing agreement",
    tags: ["productivity", "writing", "organization"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
  {
    title: "You can ask AI to simulate a user testing your product",
    prompt: "Act as a first-time user of [product]. I will walk you through the experience and you will share your honest reactions, confusion points, and expectations at each step. Be specific about what's unclear or frustrating.",
    whyItWorks: "You can't see your own product with fresh eyes. Simulating a first-time user reveals confusing UX, missing context, and broken assumptions that insiders are blind to.",
    exampleOutput: "**Step 1: Landing page**\n'I see a tagline but I still don't know what this does. Is it a tool? A service? The hero image doesn't help.'\n\n**Step 2: Signup**\n'Why do you need my company size during signup? I just want to try it. This feels like a sales funnel, not a product.'\n\n**Step 3: Dashboard**\n'Too many options. Where do I start? I'd expect a 'Get Started' wizard or a sample project...'",
    tags: ["product", "UX", "user-testing"],
    worksWith: ["Claude", "GPT-4", "Gemini"],
  },
];

// Write all files
existing.forEach((p, i) => writeMdx(i + 1, p));
newPrompts.forEach((p, i) => writeMdx(i + 26, p));

console.log(`\nDone! Wrote ${existing.length + newPrompts.length} MDX files.`);
